### PR TITLE
Randomization function v1.2

### PR DESCRIPTION
**Pull request by hitherearizona**

### CODE REVIEW

**Comment by wilpola** [comment]
Changed the base branch. We do not want to merge to the main branch directly.

**Comment by wilpola** [comment]
@hitherearizona There is a bug where the "Long Training" -option will crash the application.
flwoga1 2

**Comment by hitherearizona** [comment]
Yes, I commented it in the comment of the commit.  (I didn't know any better place to comment it)

I am not 100% sure but I think the problem is that main has not free space in the screen or programmed spot to blit so many cards, I haven't messed around with the main so much to know how to fix the issue, I would try to either fix the screen to fit more cards, or shorten the longer training.

**Review by wilpola — APPROVED** [review]
The only issue that I see is that long training does not work, but that can be fixed / added in the main repository.

**Pull request merged**
